debug: false
executable: ./predprey
output_file: predprey_parameters.sh
positions:
  - experiment_name
  - adaptation_evol
  - dist__0
  - dist__1
  - width__0
  - defence_evol
  - env_variance
  - env_variation
permutate_experiments:
  experiment_name: def_evol[<defence_evol>]-adapt_evol[<adaptation_evol>]-dist_0[<dist__0>]-dist_1[<dist__1>]-width_0[<width__0>]-env_var[<env_variance>]-env_var_on[<env_variation>]
  replicates: 8
  parameters:
    - adaptation_evol:
        - "1"
      defence_evol:
        - "0"
        - "1"
      dist__0:
        - "100"
        - "400"
        - "600"
      dist__1:
        - "400"
      width__0:
        - "1"
        - "3"
        - "5"
      env_variance:
        - "3"
        - "6"
      env_variation:
        - "1"